modifiche per re-integrazione gitea

diff --git a/release b/release
--- a/release
+++ b/release
@@ -6,10 +6,29 @@ fatal()
         exit 1
 }
 
-[[ -n $(git status --porcelain) ]] && fatal 'you should commmit before'
+[[ -n $(git status --porcelain) ]] && fatal 'you should commit before'
 
-git push || fatal 'push failed'
-A=$(./scmrev | sed -r 's/-g.*//')
-git tag "$A" || fatal 'tag failed'
-git push origin "refs/tags/$A" || fatal 'push tags failed'
+SCMVER=$(./scmrev)
+[[ -z "$SCMVER" ]] && fatal 'cannot get local version'
+TAG=$(echo "$SCMVER" | sed -r 's/-g.*//')
+git tag "$TAG" || fatal 'git tag failed'
+if ! ./dobuild ; then
+    git tag --delete "$TAG"
+    fatal 'build failed'
+fi
+if ! git push ; then 
+    git tag --delete "$TAG"
+    fatal 'push failed'
+fi
+if ! git push origin "refs/tags/$TAG" ; then
+    git tag --delete "$TAG"
+    fatal 'push tags failed'
+fi    
+sleep 5
+if ! tools/release-tea.sh "$TAG"; then
+    git push --delete origin "$TAG"
+    git tag --delete "$TAG"
+    fatal 'release to gitea failed'
+fi
+./gradlew publish || 'package to gitea failed'
 #.
